{% set version = "0.9.2" %}
{% set name = "zn_poly" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/sagemath/zn_poly/-/archive/{{ version }}/zn_poly-{{ version }}.tar.gz
  sha256: 6b4bb9f931d7ccc4cd5727faad87fbc3eed2e6a91cbd7f7c32138f6cfde39c6b

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - libtool
    - {{ compiler('c') }}
    - python *
    - make
  host:
    - gmp

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://web.maths.unsw.edu.au/~davidharvey/code/zn_poly/
  license: GPLv2+
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: zn_poly is a C library for polynomial arithmetic in Z/nZ[x], where n is any modulus that fits into an unsigned long.

extra:
  recipe-maintainers:
    - isuruf
