appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: ovY00pUBwRxMcP2x3IzekraA6u9h+zm1AaBtEPrnKWMlRWMwbcvCYUcEVQ9gnFqp/GzNsL1q503CbN/4iDmPuvY+mvKpbi2f8L2RPJrY8MJkPPJ+Ggca8o3CRCoC64qGtylrGtukI5m3TIyutDJwnllFBGaMCyoHCwCKT3r3hBno/MEYIvHVHaKHl3WDmrBhCLWH3+I0mFta1CWfsR4DDuL2hVvH2GfSUWprVuM+vFtZJ5YBjoyMT2qa+0Y2IRKVf/2/yESVT6Whay49D7kcj1igCJ+nzJ8QEd2u8xRWC0cNDfarWYu6liHZGPlu2PLbkacydZ0ZSkK6/xVQ7DB7PcDRBmhKOmsh8x0gsMgNy/qJWDgp5ANL5o7RxSrLEPBnROwlWVhEb1uv8rsY+JdKm583dQxF7HsvtoL5XlTrSnwPYrZCk4U3kL9l6r3qXQ3HWhYPAKi08Tqwdy6eE4mV9XKyrTG6hTdjIsJbsD+fvTrILTYpLi96AHw2GANElk+FTTVEwbENw+CCOxQcYSqQZFwS8jyQ1gP9h3gblO2iovh5iP7M0u5TOS/7urkZc22Y+WZYqPQKLKVgErdO6QZ8zKihFsFKxB6+vaDy5Kdf8eCoCF5mzHQZqUkK/Cgyqim5Gfnab9RwQA2lVG6vwTbdqnVPWYq9CDOsG1BpToVqKS4=}
conda_forge_output_validation: true
